name: .NET Core Backend CI  # Name der Pipeline

on:
  push:
    branches:
      - master  # Führt die Pipeline bei Pushes auf den Hauptbranch aus
  pull_request:
    branches:
      - master  # Führt die Pipeline bei Pull Requests auf den Hauptbranch aus

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Nutzt einen Linux-Runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Lädt den Code aus dem GitHub-Repository

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2  # Installiert .NET Core
        with:
          dotnet-version: '8.0'  # .NET Version

      - name: Restore dependencies
        run: dotnet restore ./WMSBackend/WMSBackend.csproj  # Stellt NuGet-Abhängigkeiten her

      - name: Build the project
        run: dotnet build ./WMSBackend/WMSBackend.csproj --no-restore  # Baut das Projekt

      - name: Run tests
        run: dotnet test ./WMSBackend.UnitTest/WMSBackend.UnitTest.csproj --logger "trx;LogFileName=TestResults.trx"
        continue-on-error: true  # Auch bei fehlgeschlagenen Tests fortfahren

      
      - name: Upload test results
        if: always()  # Führt den Schritt immer aus, auch bei fehlgeschlagenen Tests
        uses: actions/upload-artifact@v3
        with:
            name: TestResults
            path: WMSBackend.UnitTest/TestResults.trx


