name: .NET Core Backend CI  # Name der Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Ein einziger Job auf einer Linux-Umgebung

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Lädt den Code aus dem GitHub-Repository

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2  # Installiert .NET Core
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./WMSBackend/WMSBackend.csproj  # Stellt NuGet-Abhängigkeiten her

      - name: Build the project
        run: dotnet build ./WMSBackend/WMSBackend.csproj --no-restore  # Baut das Projekt

      - name: Run tests
        run: dotnet test ./WMSBackend.UnitTest/WMSBackend.UnitTest.csproj --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        if: always()  # Führt diesen Schritt aus, egal ob Tests erfolgreich sind oder nicht
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: WMSBackend.UnitTest/TestResults/TestResults.trx
